name: home
description: A new Flutter package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  list_news:
    path: ../list_news
  bookmark:
    path: ../bookmark

  dependencies:
    path: ../../libraries/dependencies
  shared:
    path: ../../libraries/shared
  core:
    path: ../../libraries/core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
