name: bookmark
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dependencies:
    path: ../../libraries/dependencies
  shared:
    path: ../../libraries/shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
