name: settings
description: A new Flutter package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../libraries/core
  dependencies:
    path: ../../libraries/dependencies
  shared:
    path: ../../libraries/shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
