name: list_news
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.5.1

  detail_news:
    path: ../detail_news

  dependencies:
    path: ../../libraries/dependencies
  shared:
    path: ../../libraries/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:
