name: dependencies
description: A new Flutter package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg:
  package_info:
  flutter_screenutil:
  easy_localization:
  cached_network_image:
  webview_flutter:
  lottie:

  # Core
  flutter_modular:
  bloc:
  dio:
  equatable:
  flutter_bloc:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
